import type { Metadata } from "next";
import "@/styles/style.scss";
import "@/styles/embla.scss";
import Background from "@/components/Background";
import MenuNavigator from "@/components/MenuNavigator";
import QrNavigator from "@/components/QrNavigator";
import Logo from "@/components/Logo";
import Qrcode from "@/components/Qrcode";
import Drawer from "@/components/Drawer";

export const metadata: Metadata = {
  title: "BODY &...",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={ "font-notosansjp " }>
        <Background/>
        <MenuNavigator>
          <Logo/>
        </MenuNavigator>
        <QrNavigator>
          <Qrcode/>
        </QrNavigator>
        <Drawer/>
        { children }
      </body>
    </html>
  );
}
